apiVersion: v1
kind: Namespace
metadata:
  name: NAMESPACE


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: NAMESPACE
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-pod
        image: ACCT.dkr.ecr.REG.amazonaws.com/REPO:VER
        ports:
        - containerPort: 80
