apiVersion: v1
kind: Namespace
metadata:
  # name: NAMESPACE
  name: api


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alex-api
  namespace: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: alex-api
        # image: ACCT.dkr.ecr.REG.amazonaws.com/REPO:VER
        image: nginx
        ports:
        - containerPort: 80
